FROM golang:1.17 as build
WORKDIR /src

RUN apt-get update && apt-get install ca-certificates -y

FROM debian:bullseye-slim
LABEL org.opencontainers.image.authors="CodeNotary, Inc. <info@codenotary.com>"

# Note: this requires running `make immuproof-release` before building the image
COPY --from=build "/etc/ssl/certs/ca-certificates.crt" "/etc/ssl/certs/ca-certificates.crt"
COPY immuproof /usr/sbin/immuproof

EXPOSE 8091

ENTRYPOINT ["/usr/sbin/immuproof", "serve"]
