name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cd:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Build
        run: make immuproof
      - name: Docker build
        run: make docker
