name: master

on:
  push:
    branches:
      - master

jobs:
  master:
    name: master
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          make test
      - name: Build
        run: |
          make immuproof
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/codenotary/immuproof:master
            codenotary/immuproof:master
      - name: Notarize git repository
        uses: docker://codenotary/cas
        with:
          args: n git://. --host cas.codenotary.com --api-key ${{ secrets.CAS_API_KEY }}
      - name: Notarize Go binary
        uses: docker://codenotary/cas
        with:
          args: n immuproof --host cas.codenotary.com --api-key ${{ secrets.CAS_API_KEY }}
      - name: Notarize docker image
        uses: docker://codenotary/cas:bom-docker
        with:
          args: n docker://codenotary/immuproof:master --host cas.codenotary.com --api-key ${{ secrets.CAS_API_KEY }}
