name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    name: pull-request
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          make test
      - name: Build
        run: |
          make immuproof
      - name: Docker build
        run:
          make docker
